# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'protobuf.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotobuf.proto\"\xf6\x01\n\rFieldsMessage\x12\x13\n\x0bint32_field\x18\x01 \x01(\x05\x12\x13\n\x0b\x66loat_field\x18\x02 \x01(\x02\x12\x14\n\x0c\x64ouble_field\x18\x03 \x01(\x01\x12\x12\n\nbool_field\x18\x04 \x01(\x08\x12\x14\n\x0cstring_field\x18\x05 \x01(\t\x12\x13\n\x0b\x62ytes_field\x18\x06 \x01(\x0c\x12\x1d\n\x15repeated_string_field\x18\x07 \x03(\t\x12\x1e\n\x0cnested_field\x18\x08 \x01(\x0b\x32\x08.Account\x12\'\n\x15repeated_nested_field\x18\t \x03(\x0b\x32\x08.Account\"\'\n\x11GetAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"P\n\x07\x41\x63\x63ount\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x12\"\n\x08settings\x18\x03 \x01(\x0b\x32\x10.AccountSettings\"$\n\x0f\x41\x63\x63ountSettings\x12\x11\n\tis_public\x18\x01 \x01(\x08\x32o\n\x0fTestCaseService\x12.\n\nTestFields\x12\x0e.FieldsMessage\x1a\x0e.FieldsMessage\"\x00\x12,\n\nGetAccount\x12\x12.GetAccountRequest\x1a\x08.Account\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIELDSMESSAGE']._serialized_start=19
  _globals['_FIELDSMESSAGE']._serialized_end=265
  _globals['_GETACCOUNTREQUEST']._serialized_start=267
  _globals['_GETACCOUNTREQUEST']._serialized_end=306
  _globals['_ACCOUNT']._serialized_start=308
  _globals['_ACCOUNT']._serialized_end=388
  _globals['_ACCOUNTSETTINGS']._serialized_start=390
  _globals['_ACCOUNTSETTINGS']._serialized_end=426
  _globals['_TESTCASESERVICE']._serialized_start=428
  _globals['_TESTCASESERVICE']._serialized_end=539
# @@protoc_insertion_point(module_scope)
